<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="css/pond-theme.css" />
    <link rel="stylesheet" href="css/pond.css" />
    {% block stylesheets %}{% endblock %}
</head>

<body>
<header>
        <nav id="mainNav" class="navbar navbar-default no-margin no-border no-radius ">
            <!-- nav class="navbar navbar-default no-margin no-border no-radius" -->

            <div class="container">
                <div id="cw_logo">
                    <img src="assets/images/logo-CodePhoenixOrg.png">
                </div>
                <div>
                    <h1 class="cw_logo_ex ">&nbsp;pond</h1>
                </div>

            </div>
        </nav>
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading">
                </div>
            </div>
        </div>
    </header>
<main>
    <section>
    {% block body %}
    {% endblock %}
    </section>
</main>
    <script src="js/pond.js"></script>
   
    {% block javascripts %}{% endblock %}


</body>

</html>
