version: "3.0"
services:
  aphpache:
    build: ./docker
    image: lap:pond
    ports:
     - '8080:80'
     - '8443:443'
    volumes:
      - .:/Sites/CodePhoenixOrg/SDK/php/Pond
      - ../Reed:/Sites/CodePhoenixOrg/SDK/php/Reed
    #command: sh -c "sudo /usr/local/bin/hop"